"""Topology layer (HANDOVER §10.3, §11.3).

Rule-based generator: samples decoy host profiles and emits
  * topology.json              (list of decoys: ip, hostname, role, os, ports, gen_type)
  * docker-compose.override.yml (one container per decoy on decnet, static IP)

cGAN conditioned on role is the stretch goal (topology/cgan/, not required).

Usage:
    python topology/generator.py --decoys 4 --seed 1
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from random import Random

import yaml

REPO = Path(__file__).resolve().parent.parent
PROFILES = Path(__file__).with_name("profiles.yaml")
DECOY_IP_START = 20  # 10.66.0.20 .. (HANDOVER §10.1: decoys .20-.39)


def generate(n: int, seed: int, gen_type: str = "llm_store") -> dict:
    prof = yaml.safe_load(PROFILES.read_text())
    roles_cfg = prof["roles"]
    rng = Random(seed)

    mix = list(prof.get("default_mix", []))
    while len(mix) < n:
        mix.append(rng.choice(list(roles_cfg)))
    mix = mix[:n]

    decoys = []
    counters: dict[str, int] = {}
    for i, role in enumerate(mix):
        ip = f"10.66.0.{DECOY_IP_START + i}"
        counters[role] = counters.get(role, 0) + 1
        hostname = f"{role}-{counters[role]:02d}"
        rc = roles_cfg[role]
        decoys.append({
            "ip": ip,
            "hostname": hostname,
            "role": role,
            "os": rc["os"],
            "protocol": rc["protocol"],
            "ports": rc["ports"],
            "gen_type": gen_type,
        })
    return {"seed": seed, "decoys": decoys}


def to_compose_override(topo: dict) -> dict:
    services = {}
    for d in topo["decoys"]:
        proto = d["protocol"]
        # All decoys share one prebuilt image (Makefile `up` builds it once);
        # giving each a `build:` would race to tag the same image name.
        svc = {
            "image": "deception-decoy:latest",
            "environment": [
                f"DECOY_IP={d['ip']}",
                "ENGINE_URL=http://orchestrator:9000",
            ],
            "networks": {"decnet": {"ipv4_address": d["ip"]}},
            "depends_on": ["orchestrator"],
            "restart": "unless-stopped",
        }
        if proto == "ssh":
            svc["command"] = ["python", "ssh_decoy.py"]
            svc["environment"].append("SSH_PORT=22")
            svc["environment"].append(
                f"SSH_BANNER={d['ports'][0]['banner']}")
        else:
            svc["command"] = ["python", "api_decoy.py"]
            svc["environment"].append("API_PORT=80")
        services[f"decoy-{d['hostname']}"] = svc

    # No top-level `networks` block: this override is always layered on the base
    # compose (`-f docker-compose.yml -f docker-compose.override.yml`), which
    # defines and creates decnet. Redeclaring it here (e.g. external) would
    # conflict with the base definition.
    return {"services": services}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--decoys", type=int, default=4)
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--gen-type", default="llm_store")
    ap.add_argument("--topology-out", default=str(REPO / "topology.json"))
    ap.add_argument("--compose-out", default=str(REPO / "docker-compose.override.yml"))
    args = ap.parse_args()

    topo = generate(args.decoys, args.seed, args.gen_type)
    Path(args.topology_out).write_text(json.dumps(topo, indent=2))

    override = to_compose_override(topo)
    Path(args.compose_out).write_text(
        "# GENERATED by topology/generator.py — do not edit by hand.\n"
        + yaml.safe_dump(override, sort_keys=False))
    print(f"wrote {args.topology_out} ({len(topo['decoys'])} decoys) and "
          f"{args.compose_out}")


if __name__ == "__main__":
    main()
